version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/apache/Dockerfile
    ports:
      - "8080:80"
    restart: always
    environment:
      DB_HOST: dpg-cv8nfman91rc7381r17g-a.oregon-postgres.render.com
      DB_NAME: iubmdb
      DB_USER: iubuser
      DB_PASS: CvexCKIHd4zOXb3jDz8eNJU1jL5002DZ
